재시작 하고 3턴 플레이되고 다음 라운드 버튼 안나옴
nextButton도 같은 방식으로
MissingReferenceException: The object of type 'Button' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
NextZone.OnBothPlayersDone () (at Assets/Scripts/UI/NextZone.cs:334)
GameManager.Update () (at Assets/Scripts/Core/GameManager.cs:299)
이렇게 되는데
private void OnDestroy()
{
    if (activePlayer != null)
    {
        // 파괴될때 델리게이트 연결 해제
        activePlayer.onNextCard -= OnNextCard;
    }
}
이것처럼 파괴할 때 뭔가 해줘야 하나?